### ISSUE TITLE
Thresholds are not working

### ISSUE THREAD

**Issue by nikhiljainonline** [kasunkv/owasp-zap-vsts-task#14]
The build succeeds even if the thresholds are crossed. For example, on enabling verification and having value of 1 for all the thresholds,
![image](https://user-images.githubusercontent.com/29748109/38299968-3017ac62-3819-11e8-890d-43e06966e9d1.png)
The build succeeds even if the alerts for medium risk and low risk is more than one.
![image](https://user-images.githubusercontent.com/29748109/38300532-accde9a0-381a-11e8-9988-b33f930a917f.png)
![image](https://user-images.githubusercontent.com/29748109/38300566-c0e919e6-381a-11e8-9417-2b04a6f2ca0a.png)

**Comment by kasunkv** [comment]
Hi, a new version of the task (v2.0.5) is released now, Please check to see if this issue still exists. If so let me know here. Sorry for the delayed response.

**Comment by denhsu** [comment]
@nikhiljainonline It works iwth v2.0.7 now.

**Comment by kingthorin** [comment]
I guess this can be closed?
