### ISSUE TITLE
##[error]Task Failed. Error: "Invalid Dsn"

### ISSUE THREAD

**Issue by NoelJK** [kasunkv/owasp-zap-vsts-task#42]
On using the task with an agent installed in same machine, its showing "##[error]Task Failed. Error: "Invalid Dsn" ". The details in task were given as follows:

Zap Api URL: localhost:8080
Api key: **************

**Comment by kasunkv** [comment]
Hi @NoelJK Are you running the build on a Private Agent that you manage? If not and if you are running the OWASP Zap on a different machine/virtual machine you need to provide an publicly accessible URL for the Zap API URL Value.

**Comment by NoelJK** [comment]
Hello @kasunkv I am running the task on an agent that i manage. Zap and the agent are present on the same machine.

**Comment by rsinghmdp** [comment]
I am facing the same issue ZAP and Agent is in same machine which i manage.
![image](https://user-images.githubusercontent.com/49229704/63838960-fdff6d80-c99b-11e9-96cc-c489089a5f27.png)

**Comment by rsinghmdp** [comment]
Hi @NoelJK are you able to resolve the issue, if yes kindly provide the resolution

**Comment by NoelJK** [comment]
@rsinghmdp No, i am yet to find a solution to this.

**Comment by rsinghmdp** [comment]
Hi @kasunkv kindly help us to resolve the issue.

**Comment by kasunkv** [comment]
I've identified the issue that is causing this. I will be able to release a new version of the task within this week.

**Comment by NoelJK** [comment]
Much appreciated!

**Comment by rsinghmdp** [comment]
@kasunkv thanks a lot, do you have any workaround till then?

**Comment by kasunkv** [comment]
Not at the moment, I am releasing a new version of the task now. It should be available for download within an hour or so. Please check the version for v2.0.9. That should fix the issue.

**Comment by kasunkv** [comment]
The new version v2.0.9 is now published. let me know if the issue persists.  Sorry for the inconvenience

**Comment by rodrigocmoreira** [comment]
But now it's always cleaning the Zap session, can you check that? Even if the checkbox is not checked

**Comment by NoelJK** [comment]
@kasunkv Task is working fine now. Thanks a lot for resolving it in such short time. :)

**Comment by kasunkv** [comment]
@rodrigocmoreira A new version with the fix for your issue is now released. Please check the version v2.0.10 is used in your pipeline. It should fix your issue. Please create a new issue if the problem persists. Closing this issue :)
