### ISSUE TITLE
Report Generator - Unable to generate HTML Report

### ISSUE THREAD

**Issue by jodachecallan** [kasunkv/owasp-zap-vsts-task#7]
Good day,

I am unable to generate an HTML Report for the Task. It Fails with the following error.

2017-09-26T08:08:06.5578098Z Generating the report...
2017-09-26T08:08:06.6359156Z (node:4928) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'name' of undefined
![image](https://user-images.githubusercontent.com/32228729/30850120-ce0fbe56-a2a4-11e7-8f42-0fa479a3c7ed.png)

I can generate an MD Report but it also displays a warning.

![image](https://user-images.githubusercontent.com/32228729/30850106-c2e8214e-a2a4-11e7-8033-3a765fd59b78.png)

**Comment by kasunkv** [comment]
Thank you for reporting this issue @jodachecallan  Will look in to this and release an update to fix this with in few days, I'll keep this thread updated with the progress.

**Comment by pnevill** [comment]
Hi, 

Same issue for me. I've tried with all the report types, but get the same error in all cases.

Any timeline on a fix/workaround for this? 

Thanks

**Comment by luismenco** [comment]
Hi,

Same issue for me. I've tried with all the report types, but get the same error in all cases.

Any timeline on a fix/workaround for this?

Thanks

**Comment by AshleyPoole** [comment]
@kasunkv I'm also getting this error as well. Any idea on a timeline in order to fix this? Not being able to publish the report from the task is a big issue.

**Comment by AshleyPoole** [comment]
FYI... Reporting options used are below. Tried HTML and XML but both fail.

Report filename: OWASP-ZAP-Report-$(Build.BuildId)
Destination Folder: $(System.DefaultWorkingDirectory)/MyAppName

**Comment by jodachecallan** [comment]
@AshleyPoole have you tried executing the scan and generating the report form the ZAP tool? just to eliminate the possibility of missing files. 
Does the MD files also not generate?

**Comment by AshleyPoole** [comment]
The scan is running from the task, it's just the report that isn't working.

I've actually already switched to using the alerts endpoint to download the report for a particular base url myself. Maybe the VSTS task should have an option to disable the report creation, or another option to use the alerts endpoint instead?

**Comment by RXtr** [comment]
Also coming up with this error. Has there been any progress on how to fix or get around this? Selecting html report fails the build, where xml and the MD file options don't fail the build, but the same error occurs in a way that the build agent doesn't care about

**Comment by AshleyPoole** [comment]
@kasunkv any update? I know you said you were busy but were going to take a look at this...

**Comment by mccright** [comment]
@kasunkv any update?  We also have this bug.  The XML & markdown reports work for our installation, but our users want the HTML reports.

**Comment by jjburr** [comment]
Any update on this, im also getting this issue.....

**Comment by kasunkv** [comment]
Hi Guys, Really sorry for the late update. Couldn't find time to get around to work on this. But, the v2.0.5 is not released.  It contains the fix for the HTML report issue and few other fixes. Check it out now and let me know of the status. Thanks for your patience.

**Comment by denhsu** [comment]
Hi @kasunkv I am using the latest v2.0.6, I have issue generating HTML and XML report, Markdown report works fine.

Here is the error when generating HTML report:
2018-05-07T22:48:28.9636359Z Generating the report...
2018-05-07T22:48:30.0466918Z ##[error]Task Failed. Error: "Cannot read property 'host' of undefined"

Here is the error when generating XML report:
2018-05-07T20:58:46.8365970Z Generating the report...
2018-05-07T20:58:49.0396146Z (node:3604) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'host' of undefined

Please let me know if you need more info.

Thanks,
Dennis

**Comment by pnevill** [comment]
Same issue for me. The Markdown report is working, but the XML/HTML is producing a "Cannot read property 'host' of undefined" error.

**Comment by denhsu** [comment]
@kasunkv Confirmed that with v2.0.7, the html and xml reports can be generated now. and the result is correct now.  this bug can be closed.
